inherit systemd pkgconfig deploy
DESCRIPTION = "Telematics Test Applications"

HOMEPAGE = "https://www.codelinaro.org/"
LICENSE = "BSD-3-Clause & BSD-3-Clause-Clear"
LIC_FILES_CHKSUM = "file://${COMMON_LICENSE_DIR}/BSD-3-Clause;md5=550794465ba0ec5312d6919e203a55f9 \
    file://${COREBASE}/meta-qti-bsp/files/common-licenses/BSD-3-Clause-Clear;md5=3771d4920bd6cdb8cbdf1e8344489ee0"

# Host dependencies
DEPENDS += "telaf-build"
DEPENDS += "telaf-image"
DEPENDS += "ninja-native"
DEPENDS += "cmake-native"
DEPENDS += "coreutils-native"

# Target dependencies
DEPENDS += "openssl"
DEPENDS += "libxml2"
DEPENDS += "xmllib"
DEPENDS += "telux"
DEPENDS += "telux-lib"

DEPENDS += "refpolicy-mls-auto"

PR = "r1"
DEBUG_BUILD="1"
FILESPATH =+ "${WORKSPACE}:"


do_configure[noexec] = "1"

FILESPATH =+ "${WORKSPACE}:"
SRC_URI += "file://telaf/"
SRC_URI += "file://legato/"

S = "${WORKDIR}/telaf"
# the TelAF stub codes generated by telaf-build.bb
S_L = "${RECIPE_SYSROOT}/telaf/legato/legato-af"

do_compile[depends] += "refpolicy-mls-auto:do_install"
do_compile() {
    export TMPDIR=${TMPDIR}
    export TARGET=${MACHINE}
    export LEGATO_ROOT=${RECIPE_SYSROOT}/telaf/legato/legato-af
    export TELAF_ROOT=${S}
    export OECORE_TARGET_SYSROOT=${RECIPE_SYSROOT}
    build_directory="${S}/testapp_build/build"
    if [ -d "$build_directory" ]; then
        rm -r "$build_directory"
    fi

    if ${@bb.utils.contains('MULTILIB_VARIANTS', 'lib32', 'true', 'false', d)}; then
        if ${@bb.utils.contains('CFLAGS', '-D_TIME_BITS=64', 'true', 'false', d)}; then
            BUILD_FLAGS="-D_TIME_BITS=64 -D_FILE_OFFSET_BITS=64"
            MKTOOLS_X_C_FLAGS="-X -D_TIME_BITS=64 -X -D_FILE_OFFSET_BITS=64"
            MKTOOLS_X_C_FLAGS+=" -C -D_TIME_BITS=64 -C -D_FILE_OFFSET_BITS=64"
            export MKTOOLS_X_C_FLAGS
        fi
    fi
    export CFLAGS="$BUILD_FLAGS -O"

    cmake -DLEGATO_TARGET=${MACHINE} -DLEGATO_ROOT=${S_L} -H${S}/testapp_build/ -B${S}/testapp_build/build
    cmake -E env CFLAGS="-O" CC="${CC} -O" CXX="${CXX} -O" cmake --build ${S}/testapp_build/build
}

do_deploy() {
    rm -rf ${DEPLOY_DIR_IMAGE}/telaf-images/testapps
    mkdir -p ${DEPLOY_DIR_IMAGE}/telaf-images/testapps/Unit_testapp
    mkdir -p ${DEPLOY_DIR_IMAGE}/telaf-images/testapps/Integration_testapp
    mkdir -p ${DEPLOY_DIR_IMAGE}/telaf-images/testapps/Console_testapp
    cp -rf ${S}/testapp_build/build/TestApps/Unit_testapp/* ${DEPLOY_DIR_IMAGE}/telaf-images/testapps/Unit_testapp/
    cp -rf ${S}/testapp_build/build/TestApps/Integration_testapp/* ${DEPLOY_DIR_IMAGE}/telaf-images/testapps/Integration_testapp/
    cp -rf ${S}/testapp_build/build/TestApps/Console_testapp/* ${DEPLOY_DIR_IMAGE}/telaf-images/testapps/Console_testapp/

}
do_deploy[dirs] = "${S} ${DEPLOYDIR}"
addtask deploy before do_build after do_install
