BBFILES += "${@bb.utils.contains('DISTRO', 'nad', '${LAYERDIR}/recipes/*/*.bb ${LAYERDIR}/recipes/*/*.bbappend ${LAYERDIR}/recipes-*/*.bb ${LAYERDIR}/recipes-products/images/*.bbappend ${LAYERDIR}/recipes-*/*.bbappend', '', d)}"
BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "telaf"
BBFILE_PRIORITY_telaf = "30"
BBFILE_PATTERN_telaf := "^${LAYERDIR}/"

PREFERRED_PROVIDER_virtual/refpolicy = "refpolicy-mls"
PREFERRED_VERSION_refpolicy-mls = "2.20170204"

LAYERSERIES_COMPAT_telaf = "${LAYERSERIES_COMPAT_core}"
