BBFILES += "${@bb.utils.contains('COMBINED_FEATURES', 'qti-nad-telaf', '${LAYERDIR}/recipes/*/*.bb ${LAYERDIR}/recipes/*/*.bbappend ${LAYERDIR}/recipes-*/*.bb ${LAYERDIR}/recipes-products/images/*.bbappend ${LAYERDIR}/recipes-*/*.bbappend ${LAYERDIR}/recipes-*/*.bbappend', '', d)}"

BBPATH .= ":${LAYERDIR}"
BBFILE_COLLECTIONS += "telaf"
BBFILE_PRIORITY_telaf = "30"
BBFILE_PATTERN_telaf = "^${LAYERDIR}/"

LAYERVERSION_telaf = "1"
LAYERSERIES_COMPAT_telaf = "dunfell"


