# Copyright (c) 2023 Qualcomm Innovation Center, Inc. All rights reserved.
# SPDX-License-Identifier: LGPL-2.1-only

lxc.arch = aarch64
lxc.console.path = none
#for mounting minmal /dev
lxc.autodev = 1
lxc.tty.max = 2
lxc.pty.max = 1

# networking
lxc.net.0.type = veth
lxc.net.0.flags = up
lxc.net.0.name = veth0
lxc.net.0.hwaddr = 4a:49:43:49:79:bf
lxc.net.0.ipv4.address = 192.168.2.2/24 192.168.2.255
#rootfs options
lxc.rootfs.path = dir:/lxcrootfs
lxc.rootfs.managed=0
lxc.rootfs.options = ro
#mounting cgroup and proc dir
lxc.mount.auto = cgroup:mixed:force proc:mixed sys:ro

#ram limit
lxc.cgroup.memory.limit_in_bytes = 20000000

# Share /dev/tty5 as /ttyMSM0
# chmod +rw /dev/tty5
# ls -l /dev/tty5
# crw-rw-rw-    1 root     tty         4,   5 Jan  6 00:00 /dev/tty5
lxc.cgroup.devices.allow = c 4:5 rw
lxc.mount.entry = /dev/tty5 dev/ttyMSM0 none bind,optional,create=file

# Prepare some sub-dirs in /data/lxc_rw for the telaf lxc container
lxc.mount.entry = /data/lxc_rw/data data none rw,bind 0 0
lxc.mount.entry = /data/lxc_rw/persist persist none rw,bind 0 0
lxc.mount.entry = /data/lxc_rw/app app none rw,bind 0 0
lxc.mount.entry = /data/lxc_rw/tmp tmp none rw,bind 0 0

lxc.uts.name = telaflxc
lxc.environment = TELAF_IN_CONTAINER=y
